name: eval notebooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://esmvfc/esm-vfc-stacks:latest
      options: --user 1001  # https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2
    steps:
    - uses: actions/checkout@v2
    - name: Run nested catalog notebook with pytest
      run: |
        python -m pytest -v -s --nbval-lax nested_catalogs_demo/nested_catalog_demo.ipynb
    - name: Run nested catalog notebook with papermill
      run: |
        pip install papermill --upgrade
        /github/home/.local/bin/papermill \
          nested_catalogs_demo/nested_catalogs_demo.ipynb
          nested_catalogs_demo/nested_catalogs_demo_output.ipynb
    - name: Upload notebook
      uses: actions/upload-artifact@v1
      with:
        name: nested_catalogs_demo_output.ipynb
        path: nested_catalogs_demo/nested_catalogs_demo_output.ipynb
