name: eval notebooks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    # Runs at 00:00 UTC on Tue
    - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://esmvfc/esm-vfc-stacks:latest
      options: --user 1001  # https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2
    steps:
    - uses: actions/checkout@v1
    - name: Initialize conda
      run: bash -c "conda init bash"
    - name: Run all notebooks with papermill
      run: |
        bash -c ". ${HOME}/.bashrc && conda activate notebook && .ci/run_all_notebooks.py --dir . --out ci_out/"
    - name: Upload notebook
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: ci_out
        path: ci_out/
