name: eval notebooks

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: docker://esmvfc/esm-vfc-stacks:latest
      options: --user 1001  # https://github.community/t/how-to-run-action-as-a-non-root-user/17572/2
    steps:
    - uses: actions/checkout@v1
    - name: Run nested catalog notebook with pytest
      run: |
        python -m pytest -v -s --nbval-lax nested_catalogs_demo/nested_catalog_demo.ipynb
    - name: Run nested catalog notebook with papermill
      run: |
        papermill --cwd nested_catalogs_demo/ nested_catalogs_demo/nested_catalog_demo.ipynb nested_catalogs_demo/nested_catalog_demo_out.ipynb
    - name: Run all notebooks with papermill
      run: |
        ci/run_all_notebooks.py --dir . --out ci_out/
    - name: Upload notebook
      uses: actions/upload-artifact@v1
      with:
        name: ci_out
        path: ci_out/
